### PR TITLE
 Add: Logging framework zerolog

### PR DESCRIPTION
**Pull request by nichtsfrei**
To be able to introduce multiple log levels zerolog is introduced.

The reason for zerolog is that it supports multiple outputs:

- Json
- CBOR
- Console

it is easy to use and has little allocations.

This will make it easy to introduce log aggregator e.g. ELK stack
without having to change logging in the modules.

The creation of the logger is done via our own package 'logging' this
will allow us to make changes in output, additional fields without
nagging the caller too much.

The different log level and our interpretation can be seen within
./docs/logging.md

### CODE REVIEW

**Comment by paulnaumann** [comment]
Just to get a better understanding of your implementation.
From what I can see, you need to initialize a new Logger instance for every package you are using a logger in. 
Doesn't this mean that the loggers would have to be reconfigured in all places, for example when the log level is adjusted?

For the greenbone-license-service we create a single logger that is generated within the main and is passed to the packages. 

The implementations can be found here:
https://github.com/greenbone/greenbone-license-service/blob/main/pkg/config/logger.go
https://github.com/greenbone/greenbone-license-service/blob/main/cmd/webApp/main.go

And what are your requirements for using sentry? Is this planned, or is this something you don't need to worry about.

**Comment by nichtsfrei** [comment]
While we could use a global logger instance https://github.com/rs/zerolog/blob/master/log/log.go#L14 and initialize it globally in our main classes, the reasoning why I choose to create one per module is that it is easier to make module only changes that way (e.g. if we want to switch from Caller information [filename:linenumber] to a nice module name indicator, that would make it easier to locate issue in a larger log aggregate]). 

To allow those without having to think about side effects or rely on _ import and `init()` magic I did prefer to create a logger instance per module explicitly, however that's purely a matter of taste.

Why are you asking questions about sentry on a logger pr?

**Comment by nichtsfrei** [comment]
Created a second commit to show the differences.

**Comment by nichtsfrei** [comment]
Also just a minor mention: you don't pass through the logger to a module but you pass it to a struct; which is a different concept and would conflict with eulabeia; because although most handlers are structs they don't have to be and logs can occur in helper functions in our case so a module approach is imho more fitting.

**Review by ArnoStiefvater — APPROVED** [review]

**Review by y0urself — APPROVED** [review]

**Pull request merged**
